In [1]:
import pandas as pd

In [4]:
import seaborn as sns

In [3]:
tips = sns.load_dataset("tips")

In [5]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
import statsmodels.formula.api as smf

In [8]:
model = smf.ols('tip ~ total_bill', data=tips) #logistic regression

In [9]:
results = model.fit()

In [10]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.457
Model:                            OLS   Adj. R-squared:                  0.454
Method:                 Least Squares   F-statistic:                     203.4
Date:                Wed, 05 Jan 2022   Prob (F-statistic):           6.69e-34
Time:                        12:22:58   Log-Likelihood:                -350.54
No. Observations:                 244   AIC:                             705.1
Df Residuals:                     242   BIC:                             712.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9203      0.160      5.761      0.000       0.606       1.235
total_bill     0.1050      0.007     14.260      0.000       0.091       0.120
==============================================================================
Omnibus:                       20.185   Durbin-Watson:                   2.151
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               37.750
Skew:                           0.443   Prob(JB):                     6.35e-09
Kurtosis:                       4.711   Cond. No.                         53.0
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [15]:
model = smf.ols('tip ~ total_bill + sex + size', data=tips) #linear regression

In [16]:
results = model.fit()

In [17]:
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.468
Model:                            OLS   Adj. R-squared:                  0.461
Method:                 Least Squares   F-statistic:                     70.36
Date:                Wed, 05 Jan 2022   Prob (F-statistic):           1.11e-32
Time:                        12:28:25   Log-Likelihood:                -347.97
No. Observations:                 244   AIC:                             703.9
Df Residuals:                     240   BIC:                             717.9
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.6555      0.206      3.178      0.002       0.249       1.062
sex[T.Female]     0.0264      0.137      0.193      0.847      -0.244       0.297
total_bill        0.0929      0.009     10.104      0.000       0.075       0.111
size              0.1926      0.085      2.253      0.025       0.024       0.361
==============================================================================
Omnibus:                       25.084   Durbin-Watson:                   2.098
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               47.089
Skew:                           0.550   Prob(JB):                     5.95e-11
Kurtosis:                       4.850   Cond. No.                         73.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
model = smf.ols('tip ~ total_bill + sex + size + day', data=tips) #linear regression
results = model.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                    tip   R-squared:                       0.469
Model:                            OLS   Adj. R-squared:                  0.456
Method:                 Least Squares   F-statistic:                     34.93
Date:                Wed, 05 Jan 2022   Prob (F-statistic):           4.04e-30
Time:                        12:32:13   Log-Likelihood:                -347.66
No. Observations:                 244   AIC:                             709.3
Df Residuals:                     237   BIC:                             733.8
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept         0.6487      0.235      2.756      0.006       0.185       1.112
sex[T.Female]     0.0326      0.141      0.231      0.818      -0.245       0.311
day[T.Fri]        0.0789      0.269      0.293      0.770      -0.451       0.609
day[T.Sat]       -0.0414      0.173     -0.239      0.811      -0.382       0.299
day[T.Sun]        0.0725      0.181      0.400      0.690      -0.284       0.429
total_bill        0.0932      0.009     10.019      0.000       0.075       0.112
size              0.1867      0.087      2.137      0.034       0.015       0.359
==============================================================================
Omnibus:                       26.163   Durbin-Watson:                   2.094
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               49.406
Skew:                           0.571   Prob(JB):                     1.87e-11
Kurtosis:                       4.886   Cond. No.                         110.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [21]:
results.params

Intercept        0.648685
sex[T.Female]    0.032595
day[T.Fri]       0.078854
day[T.Sat]      -0.041391
day[T.Sun]       0.072462
total_bill       0.093205
size             0.186741
dtype: float64

In [22]:
from sklearn import linear_model

In [23]:
lr = linear_model.LinearRegression()

In [25]:
lr.fit(x=tips['total_bill'], y=tips['tip'])

TypeError: fit() got an unexpected keyword argument 'x'

In [29]:
predicted = lr.fit(X=tips['total_bill'].values.reshape(-1,1), y=tips['tip'])

In [30]:
predicted.coef_

array([0.10502452])

In [31]:
predicted.intercept_

0.9202696135546731

In [33]:
tips_subset = tips[['tip', 'sex', 'total_bill']]

In [34]:
tips_dummy = pd.get_dummies(tips_subset, drop_first=True)

In [35]:
tips_dummy

tip  total_bill  sex_Female
0    1.01       16.99           1
1    1.66       10.34           0
2    3.50       21.01           0
3    3.31       23.68           0
4    3.61       24.59           1
..    ...         ...         ...
239  5.92       29.03           0
240  2.00       27.18           1
241  2.00       22.67           0
242  1.75       17.82           0
243  3.00       18.78           1

[244 rows x 3 columns]

In [36]:
predicted = lr.fit(tips_dummy.iloc[:,1:], tips_dummy['tip'])

In [37]:
predicted.coef_

array([0.10523236, 0.02660871])

In [39]:
from patsy import dmatrices

In [42]:
response, predictors = dmatrices('tip ~ total_bill + sex ', data = tips)

In [43]:
fited = lr.fit(predictors, response)

In [44]:
fited.coef_

array([[0.        , 0.02660871, 0.10523236]])

In [45]:
fited.intercept_

array([0.90666978])